package org.example.lesson2

const val EGLISH_LANGUAGE_SCORE_PERSON1 = 3.0
const val EGLISH_LANGUAGE_SCORE_PERSON2 = 4.0
const val EGLISH_LANGUAGE_SCORE_PERSON3 = 3.0
const val EGLISH_LANGUAGE_SCORE_PERSON4 = 5.0
fun main() {
    val averageScore: Double =
        (EGLISH_LANGUAGE_SCORE_PERSON1 + EGLISH_LANGUAGE_SCORE_PERSON2 + EGLISH_LANGUAGE_SCORE_PERSON3 + EGLISH_LANGUAGE_SCORE_PERSON4) / 4
    println(averageScore)
}